### ISSUE TITLE
Animations are not saved correctly

### ISSUE THREAD

**Issue by ficoos** [okamstudio/godot#1799] opened 2015-05-03 21:26 UTC
b2b514367824263e2dc1e26b010b0df63fd3700a broke saving of animations (and maybe other things).

How to reproduce:
* Update an animation
* Save
* All tracks are empty

**Comment by est31** [comment] 2015-05-03 23:05
Do you have an example animation file?

**Comment by reduz** [comment] 2015-05-03 23:14
no, this is right, the sort() in line 2566 should not happen and is not
neccesary, fixed in my tree, will be in next push.

**Comment by est31** [comment] 2015-05-03 23:23
That sort takes care that external resources and other things are sorted the right way. How did this occur?

**Comment by okamstudio** [comment] 2015-05-03 23:30
nope, that's the regular list of properties, which must always be saved in
the right order (otherwise stuff breaks). The order will also never change,
so sorting is not neccesary


On Sun, May 3, 2015 at 8:23 PM, est31 <notifications@github.com> wrote:

> That sort takes care that external resources and other things are sorted
> the right way. How did this occur?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1799#issuecomment-98555842>.
>



-- 

*OkamStudio*

**Closed** 2015-05-03 23:32 UTC

**Comment by est31** [comment] 2015-05-03 23:37
I can't reproduce the reorder anymore I've tried to fix with that sort.

**Comment by est31** [comment] 2015-05-04 00:01
Ah I see now, I've wanted to fix random reorders inside the `<main_resource>` tag. Those are now happening again. Still, my fix was bad I agree.

**Comment by reduz** [comment] 2015-05-04 00:33
which random reorders are you finding in the main_resource tag?

**Comment by est31** [comment] 2015-05-04 00:41
look [here](https://gist.github.com/anonymous/04b62d4d8a48228fd341). I only opened a scene, changed visibility of a node (that change isn't included), and saved.

**Comment by reduz** [comment] 2015-05-04 00:58
ah you are using a Theme, but that's to be expected because Theme saves
stuff internally in a HashMap. For regular scenes and resources this should
not happen.

**Comment by reduz** [comment] 2015-05-04 01:00
just added sorting to Theme, that also should make it easier when editing it

**Comment by est31** [comment] 2015-05-04 01:13
Thanks!

**Comment by reduz** [comment] 2015-05-04 01:40
just commited the code, please test!

**Comment by est31** [comment] 2015-05-04 15:01
Which commit does theme sorting? I can't find it.

**Comment by ficoos** [comment] 2015-05-04 19:13
Works for me. Thanks!
