### ISSUE TITLE
xml scenes reorder on saving

### ISSUE THREAD

**Issue by voidplayer** [okamstudio/godot#473] opened 2014-05-30 22:05 UTC
I know xml does not enforce any order... thats why maybe changing to other format or other  more drastic solution is due.

Thing is that is hard to keep projects under source control with more than one contributor if xml keep on changing on every save

Thanks

**Comment by est31** [comment] 2015-04-27 01:49
yea, this is really annoying.

**Comment by reduz** [comment] 2015-04-27 02:13
Xml format will go away at some point so don't get too attached to it :)

**Comment by bojidar-bg** [comment] 2015-04-29 07:02
A simple alphabetic sort can fix it... :smile:

**Comment by est31** [comment] 2015-04-29 07:50
what's its replacement? binary? xml is good because it can be easily edited with hand and better works with source control.

**Comment by reduz** [comment] 2015-04-29 11:51
the problem is that the current xml format is pseudo compressed for scenes,
so it isn't of much use.
But I guess alphabetic sorting for dictionaries makes sense

**Comment by est31** [comment] 2015-04-29 12:17
Its also needed for resources

**Comment by adolson** [comment] 2015-04-30 00:31
I guess my issue is a dupe of, or at least related to, this. #1167

**Closed** 2015-05-01 13:02 UTC
