### ISSUE TITLE
Print() 

### ISSUE THREAD

**Issue by BBric** [okamstudio/godot#1859] opened 2015-05-07 18:41 UTC
The built-in function print() should insert a space between its arguments.
```GDScript
print(1,2,3) # 1 2 3 instead of 123
```

**Comment by SuperUserNameMan** [comment] 2015-05-07 18:45
Duplicate of #1132

**Comment by reduz** [comment] 2015-05-07 18:52
use printt() which adds tabs between the arguments

**Comment by Fiona** [comment] 2015-05-07 20:20
What common use case is there for wanting tabs between items in a print statement?

It's a bit bizarre that that method exists and frustrating that print doesn't add spaces. At the very least I think it breaks the principle of least surprise.

**Comment by reduz** [comment] 2015-05-07 20:24
Maybe a new function, prints() that adds spaces is better? just to avoid
breaking it for users who may be using print regularly

**Comment by SuperUserNameMan** [comment] 2015-05-07 20:31
yep, I agree, adding a new one would be better.

**Comment by BBric** [comment] 2015-05-07 21:46
Sorry for the duplicate.
With printt() i have the same result.

**Comment by Fiona** [comment] 2015-05-07 22:36
It starts to smell a bit PHPy if you're throwing lots of little slightly different but very similar global functions around. 

In my opinion you should just have one, whatever the behaviour, and let the user do anything else manually. 

Does GDScript not have String.join()? I couldn't find it in the docs just now.

**Comment by okamstudio** [comment] 2015-05-07 22:58
Well, think of it this way. Not always the original decision is the best,
so if i change the behavior of print, the other half of users will complain
that they don't want the extra space. Most of Godot doesn't have many ways
of doing things, so in this case and given there already is a printt, I
think adding prints is the easiest solution.


On Thu, May 7, 2015 at 7:37 PM, Fiona Burrows <notifications@github.com>
wrote:

> It starts to smell a bit PHPy if you're throwing lots of little slightly
> different but very similar global functions around.
>
> In my opinion you should just have one, whatever the behaviour, and let
> the user do anything else manually.
>
> Does GDScript not have String.join()? I couldn't find it in the docs just
> now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1859#issuecomment-100039382>.
>



-- 

*OkamStudio*

**Comment by Ace-Dragon** [comment] 2015-05-07 23:27
You could already do something like...

`print(str(1)+' '+str(2)+' '+str(2))`

It will output *1 2 3* like that proposed change to the print function would do.

I think it might be sensible to not over-complicate things that are supposed to be a simple concept such as printing to the console.

**Comment by BBric** [comment] 2015-05-08 07:31
Add a space is not just cosmetic, '1 2 3' is not the same thing than '123' for a human.
If the statement 'print(a, b)' give '123', what is the value of b, 123, 23, 3 or null ? (about that null could be printed as 'null' and an empty array as '[]'). 
Additional code is required.

By against remove a space is more a cosmetic reason because the interpretation of the result is not altered, and none additional code is required.

Therefore change the current behavior would seem more justified.

**Comment by Fiona** [comment] 2015-05-08 08:04
This is my point about breaking the principle of least surprise. The syntax with commas implies some form of separation that isn't output, which is exactly why python does it to begin with.

**Comment by punto-** [comment] 2015-05-08 08:55
printt is mostly used (by me at least) for debugging. Since every other
scripting language we used before (lua, squirrel) uses tabs as separator, I
was used to doing print("values are", a, b, c, d) to quickly debug stuff on
the console, so I probably added it after Juan refused to put tabs on print
:p

I don't think the behavior of "print" is that important, since we're not
exactly a framework for text based applications, but a string formatter
would be nice to have for cases where we need to localize strings with
parameters..

**Comment by bojidar-bg** [comment] 2015-05-10 15:11
That should get closed I guess :smile:

**Closed** 2015-05-10 17:20 UTC

**Comment by BBric** [comment] 2015-05-11 21:02
Thanks.

**Comment by yaboiteedoh** [comment] 2024-03-21 13:35
Seems weird to me that GDScript doesn't lean on python in this way by implementing a "sep" optional parameter in the same way python's print works

**Comment by bojidar-bg** [comment] 2024-03-22 13:52
@yaboiteedoh Fair enough. You might want to make [a proposal](https://github.com/godotengine/godot-proposals) about it, though, make sure you glance through https://github.com/godotengine/godot-proposals/issues/902 for some of the technical details on why named arguments are hard to implement in GDScript at the time (:

**Comment by yaboiteedoh** [comment] 2024-03-22 13:54
I appreciate the insight, decided to look through the source code to see if there's any way I could finagle some kind of makeshift solution but I've never contributed to open source and have limited lower level knowledge so it was pretty dizzying lol
