### ISSUE TITLE
godot game crash in "Bullet shower" demo 

### ISSUE THREAD

**Issue by gra-frogger** [okamstudio/godot#1753] opened 2015-04-28 08:17 UTC
hey i have found a costant bug, godot game close, I think, to this point that not is error of my game, anyway try "Bullet shower" demo, the bug not is present in 1.0 , but if i test the demo with 1.1 the bug apppear when I collide with 3-2 bullet.

**Comment by gra-frogger** [comment] 2015-04-28 09:10
the terminal errors:

2d/shower_of_bullets -rdebug localhost:6007 res://shower.scn
ERROR: set_stream_peer: Condition ' p_peer.is_null() ' is true.
   At: core/io/packet_peer.cpp:228.


table/2d/shower_of_bullets/data.pck, -1, -1
has connection!
has connection!
CLOSING CONNECTION
ERROR: set_stream_peer: Condition ' p_peer.is_null() ' is true.
   At: core/io/packet_peer.cpp:228.

freed code id 5
freed code id 4
ERROR: free: Method/Function Failed.
   At: servers/visual/visual_server_raster.cpp:4659.
freed code id 6
ERROR: free: Method/Function Failed.
   At: servers/visual/visual_server_raster.cpp:4659.
ERROR: free: Method/Function Failed.
   At: servers/visual/visual_server_raster.cpp:4659.
ERROR: set_stream_peer: Condition ' p_peer.is_null() ' is true.
   At: core/io/packet_peer.cpp:228.
base resources missing 2
ERROR: finish: Condition ' instance_dependency_map.size() ' is true.
   At: servers/visual/visual_server_raster.cpp:7483.
ERROR: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1723.

**Comment by volzhs** [comment] 2015-04-28 10:59
I guess it's duplicated issue with #1592

**Comment by bojidar-bg** [comment] 2015-04-28 13:15
I too think it is a duplicate of #1592

**Comment by reduz** [comment] 2015-04-29 00:37
this seems fixed

**Comment by reduz** [comment] 2015-04-29 00:37
(can't reproduce)

**Comment by Ace-Dragon** [comment] 2015-04-29 18:45
I recall that there was a commit that fixed this in the days after the 1.1 beta release.

Grab any new build done either on your own or by Marynate and you shouldn't have any crashes.

**Closed** 2015-05-01 14:45 UTC
