### ISSUE TITLE
custom theme button decoration does not work. Font becomes erased upon pressing and in focused mode.

### ISSUE THREAD

**Issue by choikwa** [okamstudio/godot#2046] opened 2015-06-08 07:01 UTC
Following https://github.com/okamstudio/godot/wiki/tutorial_gui_skinning, I noticed that custom themed button does not properly display pressed/focused mode. Hover works.

**Comment by choikwa** [comment] 2015-06-08 07:05
Cleaning up button.cpp, base_button.cpp abit. I think I got it almost working. Not sure why focused is showing ERROR in decoration. Unsure how to debug cause of that.. it goes behind a visual server raster, which I'm not familiar with.

**Comment by choikwa** [comment] 2015-06-08 07:17
Fixed. Problem was style = get_stylebox("focus"); instead of "focused" :)

**Comment by choikwa** [comment] 2015-06-08 07:31
Pull request #2047

**Comment by volzhs** [comment] 2015-06-08 11:21
I had same problem and I noticed focused ``StyleBoxTexture`` should be unchecked ``Draw Center`` property.
Then it seems to work.

**Comment by reduz** [comment] 2015-06-08 12:55
Yes, this is not a bug, focus is drawn as an overlay, it's not a button state as you can press, hover and release when a button is focused.

**Comment by reduz** [comment] 2015-06-08 12:57
If you want a more custom behavior, you can make a simple script that inherits BaseButton and override the _draw() function, using get_draw_mode() to know what you have to draw and overriding get_minimum_size() to specify to the UI how big the button is.

**Comment by reduz** [comment] 2015-06-08 13:09
not a bug, focus is an overlay

**Comment by choikwa** [comment] 2015-06-08 13:37
The bug is that when focus is drawn as an overlay, but it draws over everything else. As a result, when focus is opaque, it clobbers everything on the button.

**Comment by reduz** [comment] 2015-06-08 13:39
pushed a fix, making focus draw before the text

**Closed** 2015-06-08 16:54 UTC
